### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by ghost** [apokryptein/secinject#1]
nothing happens when trying the bof, no output no debug message to understand what happens.
is there any fix?? any help please?

**Comment by apokryptein** [comment]
I've added NTSTATUS error checks to the BOF, but it is working just fine for me.  If you don't get any error messages, it may be that the injection is triggering the target system's AV or firewall.  If you are testing this using an unencrypted channel (such as HTTP vs HTTPS) it will get caught by Windows Firewall if not disabled.
