### ISSUE TITLE
Not working with cobalt strike 4.5

### ISSUE THREAD

**Issue by ScriptIdiot** [apokryptein/secinject#2]
Seems its not working with CS 4.5 but works fine with 4.4.
Thank you for the work btw!

**Comment by apokryptein** [comment]
There seemed to be an issue with how the Aggressor Script was generating the payload dynamically for injection; thanks for bringing it to my attention.  Should be working now!

**Comment by ScriptIdiot** [comment]
Thank you for the update but sadly its not working, looks like the syntax of aggressor has been changed for CS4.5, wanted to debug but then the official website of aggressor is currently down LOL

**Comment by apokryptein** [comment]
Hmm, interesting.  What issue are you having specifically?  I tested it in CS 4.5, but if you could share exactly what problem you're encountering so I can try to replicate it, that would be awesome!  Try re-cloning the repo first.

I had some issues accessing the Aggressor documentation as well; I think they migrated it recently.  You can find it here:
https://download.cobaltstrike.com/aggressor-script/index.html

**Comment by ScriptIdiot** [comment]
Thank you for your prompt reply! it was doing nth, no response, no beacon after issuing the command. (I have tried re-cloning and recompile + directly using your object file(both new and old), both failed).
Will try to debug from my side as well. Thanks!

**Comment by ghost** [comment]
the the hook for sec-inject is not working, for sec-shinject however its ok on CS.4.4.

its only a problem concerning sec-inject , not output in the beacon console weird , as if this part of cna is completely ignored , nothing on script console also.

**Comment by ScriptIdiot** [comment]
same as above, sec-shinject works in CS4.5 while sec-inject doest (no response in console)

The below listeners do not exist in my CS but just to show the aggressor is not working as intended
![image](https://user-images.githubusercontent.com/21979646/148077320-ab14e9b3-7957-46a3-b480-ef1cba4d58b5.png)
![image](https://user-images.githubusercontent.com/21979646/148077430-7bc401de-aa24-4ab2-a19d-b4255727b56d.png)

**Comment by ghost** [comment]
1) @ScriptIdiot man in the sec-shinject you must provide a PID of target and the .bin x64 

2) @ScriptIdiot  for sec-inject you lust provide the PID and listener(one of the listener you have in teamserver http; https;smb..)

**Comment by ScriptIdiot** [comment]
> 1. @ScriptIdiot man in the sec-shinject you must provide a PID of target and the .bin x64
> 2. @ScriptIdiot  for sec-inject you lust provide the PID and listener(one of the listener you have in teamserver http; https;smb..)

Sure I know, i just want to show that the cna should check if the PID is an integer and if that listeners exist, above screenshot just aiming to show the cna is not working

**Comment by ghost** [comment]
ahhh i see you were just checking the hooks intended to tell you if listener exists or not okkk :))

weird because the sec-shinject works ok for me on Cs4.4, however sec-inject to working at all , it accepts params
but not outputing anything on the console.

**Comment by ScriptIdiot** [comment]
> ahhh i see you were just checking the hooks intended to tell you if listener exists or not okkk :))
> 
> weird because the sec-shinject works ok for me on Cs4.4, however sec-inject to working at all , it accepts params but not outputing anything on the console.

yes i am experiencing the same, sec-shinject works fine on CS4.5 even the cna is not really working on checking parameter, but then for sec-inject is not working at all.

**Comment by ghost** [comment]
can i dm you in private ? do you a Tox ID or email?

**Comment by ScriptIdiot** [comment]
may you discord me? ScriptIdiot#9158

**Comment by ghost** [comment]
ok I'm adding you now

**Comment by apokryptein** [comment]
Just updated the Aggressor script to fix some of the error checking issues.  Please take a look and let me know if you run into any other issues. @ScriptIdiot  @fendi1989

**Comment by ScriptIdiot** [comment]
Its working now with changing the cna as in pull request, thanks!!
